### ISSUE TITLE
Session metrics collecting error in Action

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#1013]
[Spotlight Schools sessions action](https://github.com/news-catalyst/next-tinynewsdemo/runs/4689378092?check_suite_focus=true) is throwing an error:

```
[{"dimensions":["20220102"],"metrics":[{"values":["1"]}]}]
(node:1844) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
    at getNodeRequestOptions (/home/runner/work/next-tinynewsdemo/next-tinynewsdemo/node_modules/node-fetch/lib/index.js:1305:9)
    at /home/runner/work/next-tinynewsdemo/next-tinynewsdemo/node_modules/node-fetch/lib/index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (/home/runner/work/next-tinynewsdemo/next-tinynewsdemo/node_modules/node-fetch/lib/index.js:1407:9)
    at fetchGraphQL (/home/runner/work/next-tinynewsdemo/next-tinynewsdemo/script/shared.js:785:24)
    at Object.hasuraInsertSession (/home/runner/work/next-tinynewsdemo/next-tinynewsdemo/script/shared.js:468:10)
    at rows.forEach (/home/runner/work/next-tinynewsdemo/next-tinynewsdemo/script/ga.js:504:10)
    at Array.forEach (<anonymous>)
    at storeData (/home/runner/work/next-tinynewsdemo/next-tinynewsdemo/script/ga.js:282:8)
    at importDataFromGA (/home/runner/work/next-tinynewsdemo/next-tinynewsdemo/script/ga.js:613:5)
(node:1844) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1844) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Interestingly, the BBG Sessions metrics collector has similar-looking data but doesn't throw an error:

```
[{"dimensions":["20220102"],"metrics":[{"values":["6"]}]}]
hasura insert result: { data:
   { insert_ga_sessions_one:
      { updated_at: '2022-01-03T09:11:03.928381+00:00',
        id: 4830,
        created_at: '2022-01-03T09:11:03.928381+00:00',
        count: 6,
        date: '2022-01-02',
        organization_id: 109 } } }
data import ok
```

**Comment by jacqui** [comment]
Ohhh I think I know what this must be - a missing environment variable, probably the api url for hasura, specific to the Spotlight Schools env.

**Comment by jacqui** [comment]
Okay yes - that was the problem, a missing environment variable for the hasura api url.

The [github action for spotlight schools](https://github.com/news-catalyst/next-tinynewsdemo/runs/4693935529?check_suite_focus=true) is running fine now and collecting sessions data.
