### ISSUE TITLE
Data importer error: apiToken not defined

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#1045]
```
error importing data into hasura: ReferenceError: apiToken is not defined
    at importDataFromGA (/home/runner/work/next-tinynewsdemo/next-tinynewsdemo/script/ga.js:616:18)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jacqui** [comment]
Once I fixed this bug I ran into another issue:

```
stored data import status: {
  errors: [
    {
      extensions: [Object],
      message: 'unexpected variables in variableValues: success, row_count'
    }
  ]
}
```

I figured out how to run this locally - I had trouble doing that last week, which is partly why these issues slipped through into  the GH action - and can make sure the full e2e action works before opening a PR with the fixes 👍
