### ISSUE TITLE
Rate exceeded exception when building app

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#117]
Not good!

```
Error occurred prerendering page "/tags/protest". Read more: https://err.sh/next.js/prerender-error
Error: Rate Exceeded.: {"response":{"errors":[{"message":"Rate Exceeded.","locations":[{"line":7,"column":9}],"path":["listBasicArticles","data",4,"category"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"message":"Rate Exceeded.","code":"TooManyRequestsException","time":"2020-09-16T18:28:30.244Z","requestId":"66f02116-0cbe-4081-b727-c83f8b4cc872","statusCode":429,"retryable":true,"stacktrace":["TooManyRequestsException: Rate Exceeded.","    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)","
```

**Comment by TylerFisher** [comment]
FWIW it built perfectly fine on vercel.

**Comment by jacqui** [comment]
So was that error reported on your localhost? I have't seen this one before :o But I'll take a look at the tag index page to see if I can figure out what's going on with the prerendering...

**Comment by jacqui** [comment]
I'm hopeful that we won't run into this issue after the changes in PR #127 which drastically reduce the number of API calls made to Webiny. FWIW I did run into this exact error a few times while trying to streamline the build process; once I added in the reading data from cache function, the error went away.

**Comment by jacqui** [comment]
Argh I take that back. I just got this error again, using the branch with caching!

Maybe it's something about this tag index page? I've only seen it triggered by that page. I'm investigating. 

```
Error occurred prerendering page "/tags/newbietag". Read more: https://err.sh/next.js/prerender-error
Error: Rate Exceeded.: {"response":{"errors":[{"message":"Rate Exceeded.","locations":[{"line":7,"column":9}],"path":["listBasicArticles","data",6,"category"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"message":"Rate Exceeded.","code":"TooManyRequestsException","time":"2020-09-24T04:09:15.551Z","requestId":"a6bd26dc-f692-4017-b5eb-a9170ea7778e","statusCode":429,"retryable":true,"stacktrace":["TooManyRequestsException: Rate Exceeded.","    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:51:27)","    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)","    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)","    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)","    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:688:14)","    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)","    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)","    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10","    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)","    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:690:12)"]}}}
```

**Comment by jacqui** [comment]
a little update: this seems like an AWS error not a webiny error. I found some people reporting it in the webiny slack and was able to find the error documented in AWS. I'll try to find warnings/alerts in our AWS console...  maybe this is a configurable setting? Otherwise it would kinda suck to actually slow down the build process to avoid this error :-/

**Comment by jacqui** [comment]
I don't think we get this error anymore, we don't make as many requests in a short amount of time now. Closing this, but we should keep it in mind.
