### ISSUE TITLE
Support i18n site metadata

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#212]
I think I forgot about the metadata part of the site config when I was rolling out all the i18n stuff.

this should save in the default locale (en-US) when editing at http://localhost:3000/tinycms/config/metadata and then save in spanish (es locale) when editing at http://localhost:3000/es/tinycms/config/metadata

**Comment by jacqui** [comment]
Just FYI, this required a change to the model & gql schema: https://github.com/news-catalyst/reproducible-tinynews-content-api/pull/51

**Comment by jacqui** [comment]
Just found a bug in master after PR #215 was merged:

```
Error: Field "data" must not have a selection since type "String" has no subfields.: {"response":{"errors":[{"message":"Field \"data\" must not have a selection since type \"String\" has no subfields.","locations":[{"line":6,"column":14}],"extensions":{"code":"GRAPHQL_VALIDATION_FAILED","exception":{"stacktrace":["GraphQLError: Field \"data\" must not have a selection since type \"String\" has no subfields.","    at Object.Field (/var/task/handler.js:23182:33)","    at Object.enter (/var/task/handler.js:3868:29)","    at Object.enter (/var/task/handler.js:3918:25)","    at visit (/var/task/handler.js:3786:26)","    at Module.validate (/var/task/handler.js:10593:68)","    at validate (/var/task/handler.js:47065:34)","    at Object.<anonymous> (/var/task/handler.js:46962:42)","    at Generator.next (<anonymous>)","    at fulfilled (/var/task/handler.js:46849:58)"]}}}],"status":400},"request":{"query":"{\n  siteMetadatas {\n    listSiteMetadatas {\n      data {\n        id\n        data {\n          values {\n            locale\n            value\n          }\n        }\n        published\n        firstPublishedOn\n        lastPublishedOn\n      }\n    }\n  }\n}"}}
```

**Comment by jacqui** [comment]
Oh actually, I think this bug is because I haven't redeployed the API that site is hitting - it's from one of my test launch-a-new-tiny-news-org front-ends.

I'll verify that now.

**Comment by jacqui** [comment]
Okay, that bug ☝️ on `Field "data" must not have a selection...` was indeed due to the API not being deployed.

Now I've run into another wrinkle though: I had siteMetadata defined as a string, added content, then deployed the API with the change turning siteMetadata.data into an i18nString field (`values[].value|locale`). I believe this is causing the following error when trying to list siteMetadata:

```
{
  "errors": [
    {
      "message": "Cannot use 'in' operator to search for 'values' in \"{\\n   \\\"shortName\\\":\\\"The Oaklyn Observer\\\",\\n   \\\"siteUrl\\\":\\\"https://tinynewsco.org/\\\",\\n   \\\"homepageTitle\\\":\\\"The Oaklyn Observer\\\",\\n   \\\"homepageSubtitle\\\":\\\"a local news initiative\\\",\\n   \\\"subscribe\\\":{\\n      \\\"title\\\":\\\"Subscribe\\\",\\n      \\\"subtitle\\\":\\\"Get the latest news about the tiny news collective in your inbox.\\\"\\n   },\\n   \\\"footerTitle\\\":\\\"tinynewsco.org\\\",\\n   \\\"footerBylineName\\\":\\\"News Catalyst\\\",\\n   \\\"footerBylineLink\\\":\\\"https://newscatalyst.org\\\",\\n   \\\"labels\\\":{\\n      \\\"latestNews\\\":\\\"Latest News\\\",\\n      \\\"search\\\":\\\"Search\\\",\\n      \\\"topics\\\":\\\"Topics\\\"\\n   },\\n   \\\"nav\\\":{\\n      \\\"articles\\\":\\\"Articles\\\",\\n      \\\"topics\\\":\\\"All Topics\\\",\\n      \\\"cms\\\":\\\"tinycms\\\"\\n   },\\n   \\\"searchTitle\\\":\\\"The Oaklyn Observer\\\",\\n   \\\"searchDescription\\\":\\\"Page description\\\",\\n   \\\"facebookTitle\\\":\\\"Facebook title\\\",\\n   \\\"facebookDescription\\\":\\\"Facebook description\\\",\\n   \\\"twitterTitle\\\":\\\"Twitter title\\\",\\n   \\\"twitterDescription\\\":\\\"Twitter description\\\"\\n}\"",
      "path": [
        "siteMetadatas",
        "listSiteMetadatas"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "serviceName": "API_TINYNEWS_MODELS",
        "query": "{siteMetadatas{listSiteMetadatas{data{id}}}}",
        "variables": {},
        "exception": {
          "stacktrace": [
            "TypeError: Cannot use 'in' operator to search for 'values' in \"{\\n   \\\"shortName\\\":\\\"The Oaklyn Observer\\\",\\n   \\\"siteUrl\\\":\\\"https://tinynewsco.org/\\\",\\n   \\\"homepageTitle\\\":\\\"The Oaklyn Observer\\\",\\n   \\\"homepageSubtitle\\\":\\\"a local news initiative\\\",\\n   \\\"subscribe\\\":{\\n      \\\"title\\\":\\\"Subscribe\\\",\\n      \\\"subtitle\\\":\\\"Get the latest news about the tiny news collective in your inbox.\\\"\\n   },\\n   \\\"footerTitle\\\":\\\"tinynewsco.org\\\",\\n   \\\"footerBylineName\\\":\\\"News Catalyst\\\",\\n   \\\"footerBylineLink\\\":\\\"https://newscatalyst.org\\\",\\n   \\\"labels\\\":{\\n      \\\"latestNews\\\":\\\"Latest News\\\",\\n      \\\"search\\\":\\\"Search\\\",\\n      \\\"topics\\\":\\\"Topics\\\"\\n   },\\n   \\\"nav\\\":{\\n      \\\"articles\\\":\\\"Articles\\\",\\n      \\\"topics\\\":\\\"All Topics\\\",\\n      \\\"cms\\\":\\\"tinycms\\\"\\n   },\\n   \\\"searchTitle\\\":\\\"The Oaklyn Observer\\\",\\n   \\\"searchDescription\\\":\\\"Page description\\\",\\n   \\\"facebookTitle\\\":\\\"Facebook title\\\",\\n   \\\"facebookDescription\\\":\\\"Facebook description\\\",\\n   \\\"twitterTitle\\\":\\\"Twitter title\\\",\\n   \\\"twitterDescription\\\":\\\"Twitter description\\\"\\n}\"",
            "    at FieldsStorageAdapter.fromStorage (/var/task/handler.js:95863:16)",
            "    at Array.FieldsStorageAdapter.fields.fields (/var/task/handler.js:95808:20)",
            "    at FieldsStorageAdapter.fromStorage (/var/task/handler.js:95870:53)",
            "    at baseFn.populateFromStorage (/var/task/handler.js:95459:55)",
            "    at Function.find (/var/task/handler.js:95647:29)",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ],
  "data": {
    "siteMetadatas": {
      "listSiteMetadatas": null
    }
  }
}
```

My takeaway on this is that ... we need to clear out content in the old model before restructuring it? 😬 It's not great at least. I would delete this siteMetadata record - it's test data only, after all - but to do that, I need the ID. I can't get the ID without listing the records, which isn't working even when only requesting the `id` field.

Before I wipe this API stack completely and redeploy it 😬 I am going to try figuring out a way to basically `DELETE * FROM SITE_METADATAS` only in graphql. I feel like, while it's a dangerous operation, we should have a way of doing this. Otherwise we'll have to relaunch the entire API which is just... wild. Or... maybe connect to the mongo db and wipe the collection?

**Comment by jacqui** [comment]
I've confirmed that the following works when changing a content model:

* delete data in the current model's format
* deploy the new model

I'm not sure how to remodel content without removing it first, at least not for changing a regular string to the special `i18nString`.
