### ISSUE TITLE
Build error on new static page template

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#363]
```
Unhandled error during request: TypeError: Cannot read property 'page_translations' of undefined
--
10:27:29.192 | at StaticPage (/vercel/workpath0/.next/serverless/pages/static/[slug].js:2876:30)
10:27:29.192 | at d (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:33:498)
10:27:29.193 | at bb (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:16)
10:27:29.193 | at a.b.render (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:42:43)
10:27:29.193 | at a.b.read (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:41:83)
10:27:29.193 | at exports.renderToString (/vercel/workpath0/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:52:138)
10:27:29.193 | at Object.renderPage (/vercel/workpath0/node_modules/next/dist/next-server/server/render.js:52:851)
10:27:29.193 | at Function.getInitialProps (/vercel/workpath0/.next/serverless/pages/static/[slug].js:3462:19)
10:27:29.193 | at loadGetInitialProps (/vercel/workpath0/node_modules/next/dist/next-server/lib/utils.js:5:101)
10:27:29.193 | at renderToHTML (/vercel/workpath0/node_modules/next/dist/next-server/server/render.js:52:1142)
```

**Comment by jacqui** [comment]
This was because the page paths were using "fallback: true" but the page itself wasn't handling that with a check on `if (router.fallback)`
