### ISSUE TITLE
Use of !important in css fails AMP validation

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#56]
/?amp=1  error  The text inside tag 'style amp-custom' contains 'CSS !important', which is disallowed.  https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/#stylesheets

> Build error occurred
Error: AMP Validation caused the export to fail. https://err.sh/vercel/next.js/amp-export-validation
    at exportApp (/Users/jacqui/Projects/newscatalyst/review-webiny/next-tinynewsdemo/node_modules/next/dist/export/index.js:22:1036)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async build (/Users/jacqui/Projects/newscatalyst/review-webiny/next-tinynewsdemo/node_modules/next/dist/build/index.js:36:218)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jacqui** [comment]
Fixed by removing `!important` from the two css directives that included it...
