### ISSUE TITLE
error  The parent tag of tag 'img' is 'article', but it can only be 'i-amphtml-sizer-intrinsic'.

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#57]
When running `yarn run build`, build fails on:

Amp Validation

/articles/[category]/[slug]?amp=1  error  The parent tag of tag 'img' is 'article', but it can only be 'i-amphtml-sizer-intrinsic'.

> Build error occurred
Error: AMP Validation caused the export to fail. https://err.sh/vercel/next.js/amp-export-validation
    at exportApp (/Users/jacqui/Projects/newscatalyst/review-webiny/next-tinynewsdemo/node_modules/next/dist/export/index.js:22:1036)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async build (/Users/jacqui/Projects/newscatalyst/review-webiny/next-tinynewsdemo/node_modules/next/dist/build/index.js:36:218)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by jacqui** [comment]
Fixed - the mainImage handling needed to accommodate for AMP in the article template.
