### ISSUE TITLE
Errors building newly bootstrapped test org

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#633]
These are all most likely due to some required data being missing - and if so, I need to add that setup to the `yarn bootstrap` command.

*Update* I think the site metadata isn't being created correctly with a "translation" record. Also, I had forgotten to set the LOCALES env to "en-US" only as this test org only publishes in the one language; the same errors occur, only in one set of pages instead of two.

```

$ next build
--
11:48:14.463 | warn  - React 17.0.1 or newer will be required to leverage all of the upcoming features in Next.js 11. Read more: https://err.sh/next.js/react-version
11:48:14.469 | info  - Creating an optimized production build...
11:48:14.485 | Attention: Next.js now collects completely anonymous telemetry regarding usage.
11:48:14.485 | This information is used to shape Next.js' roadmap and prioritize features.
11:48:14.485 | You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
11:48:14.485 | https://nextjs.org/telemetry
11:48:16.102 | info  - Using external babel configuration from /vercel/path0/.babelrc.js
11:48:50.425 | info  - Compiled successfully
11:48:50.425 | info  - Collecting page data...
11:48:52.747 | info  - Generating static pages (0/24)
11:48:53.473 | Browserslist: caniuse-lite is outdated. Please run:
11:48:53.474 | npx browserslist@latest --update-db
11:48:53.733 | info  - Generating static pages (6/24)
11:48:53.782 | AMP Optimizer SeparateKeyframes WARNING Found invalid keyframe property '-webkit-animationTimingFunction' in 'keyframes' not moving to style[amp-keyframes]
11:48:54.092 | Unhandled error during request: TypeError: Cannot read property 'site_metadata_translations' of undefined
11:48:54.092 | at getStaticProps (/vercel/path0/.next/serverless/pages/404.js:8221:43)
11:48:54.092 | at processTicksAndRejections (internal/process/task_queues.js:93:5)
11:48:54.092 | at async renderToHTML (/vercel/path0/node_modules/next/dist/next-server/server/render.js:28:109)
11:48:54.092 | at async renderReqToHTML (/vercel/path0/.next/serverless/pages/404.js:1995:334)
11:48:54.092 | at async /vercel/path0/node_modules/next/dist/export/worker.js:12:92
11:48:54.092 | at async /vercel/path0/node_modules/next/dist/build/tracer.js:1:1441
```

```

Unhandled error during request: TypeError: Cannot read property 'landingPage' of undefined
--
11:48:54.891 | at getStaticProps (/vercel/path0/.next/serverless/pages/index.js:5738:20)
11:48:54.891 | at processTicksAndRejections (internal/process/task_queues.js:93:5)
11:48:54.892 | at async renderToHTML (/vercel/path0/node_modules/next/dist/next-server/server/render.js:28:109)
11:48:54.892 | at async renderReqToHTML (/vercel/path0/.next/serverless/pages/index.js:2163:334)
11:48:54.892 | at async /vercel/path0/node_modules/next/dist/export/worker.js:12:92
11:48:54.892 | at async /vercel/path0/node_modules/next/dist/build/tracer.js:1:1441
```

Full output https://vercel.com/news-catalyst/bello/41iLmWMUnQ4C2JWm9z1c3S56VAFF

**Comment by jacqui** [comment]
Doh!

I forgo to update the webhook with the current organization ID and slug. Now it all works fine.
