### ISSUE TITLE
Webhook error after bootstrapping new org: ERR_HTTP_HEADERS_SENT

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#716]
I tried to authenticate using the new org details that I set with `yarn bootstrap` but the webhook is failing. The org is correctly added to the organizations table in Hasura.

The response from the webhook is odd:

```
± |develop U:2 ?:5 ✗| → curl https://cdm1ipq6q5.execute-api.us-east-1.amazonaws.com/prod/webhook -H "TNC-Organization: placeholder-tiny-org"
{"error":"No organization found for slug placeholder-tiny-org"}
```

Clearly though the query being used in the webhook does work in the hasura console, also using the admin secret:

<img width="974" alt="Screen Shot 2021-07-26 at 11 32 56 am" src="https://user-images.githubusercontent.com/3397/126921553-0fbd1e0f-3399-4477-9593-b079cd7a7812.png">

[CloudWatch logs](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252FServerlessExpressStack-ExpressLambdaFunction-18DA72T2HG7UQ/log-events/2021$252F07$252F26$252F$255B$2524LATEST$255De88093ad0c20484c93ce3e05469b950e) show the following:

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:530:11)
    at ServerResponse.set (/var/task/webpack:/webhook/node_modules/express/lib/response.js:771:10)
    at ServerResponse.send (/var/task/webpack:/webhook/node_modules/express/lib/response.js:170:12)
    at ServerResponse.json (/var/task/webpack:/webhook/node_modules/express/lib/response.js:267:15)
    at fn (/var/task/webpack:/webhook/src/app.js:61:12)
    at r.handle_request (/var/task/webpack:/webhook/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/task/webpack:/webhook/node_modules/express/lib/router/route.js:137:13)
    at p.fn [as dispatch] (/var/task/webpack:/webhook/node_modules/express/lib/router/route.js:112:3)
    at r.handle_request (/var/task/webpack:/webhook/node_modules/express/lib/router/layer.js:95:5)
    at /var/task/webpack:/webhook/node_modules/express/lib/router/index.js:281:22
```

**Comment by jacqui** [comment]
Okay I figured it out. The error above was a bit of a red herring - the issue was that the testing webhook/hasura credentials were being set on the production webhook. The testing db was a copy of the live one, but it wouldn't have the latest `yarn boostrap` data for a new org.
