### ISSUE TITLE
Environment did not get written to Vercel

### ISSUE THREAD

**Issue by TylerFisher** [news-catalyst/next-tinynewsdemo#817]
I tried to bootstrap Austin Vida, and I got an environment file created locally that looks correct, but none of the env vars got written to Vercel.

**Comment by TylerFisher** [comment]
```[vercel] error creating project: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.createProject (/Users/tylerfisher/src/next-tinynewsdemo/script/vercel.js:107:31)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
