### ISSUE TITLE
geo-sessions data importer error on absolute urls

### ISSUE THREAD

**Issue by jacqui** [news-catalyst/next-tinynewsdemo#959]
```
(node:1735) UnhandledPromiseRejectionWarning: TypeError: Only absolute URLs are supported
   at getNodeRequestOptions (/home/runner/work/next-tinynewsdemo/next-tinynewsdemo/node_modules/node-fetch/lib/index.js:1305:9)
    at /home/runner/work/next-tinynewsdemo/next-tinynewsdemo/node_modules/node-fetch/lib/index.js:1410:19
    at new Promise (<anonymous>)
    at fetch (/home/runner/work/next-tinynewsdemo/next-tinynewsdemo/node_modules/node-fetch/lib/index.js:1407:9)
    at fetchGraphQL (/home/runner/work/next-tinynewsdemo/next-tinynewsdemo/script/shared.js:785:24)
    at Object.hasuraInsertGeoSession (/home/runner/work/next-tinynewsdemo/next-tinynewsdemo/script/shared.js:443:10)
    at rows.forEach (/home/runner/work/next-tinynewsdemo/next-tinynewsdemo/script/ga.js:326:10)
    at Array.forEach (<anonymous>)
    at storeData (/home/runner/work/next-tinynewsdemo/next-tinynewsdemo/script/ga.js:277:8)
    at importDataFromGA (/home/runner/work/next-tinynewsdemo/next-tinynewsdemo/script/ga.js:600:5)
```

https://github.com/news-catalyst/next-tinynewsdemo/runs/4158535868?check_suite_focus=true

Frustratingly, the action finishes with a success status. As part of fixing the above error it would be really good to figure out why the action isn't being labelled as failing.

**Comment by jacqui** [comment]
Aha, this was actually due to BBG's GitHub env missing values for several important env vars, including the `HASURA_API_URL` - fixed now.
